spring.application.name=api
server.port=8080

# Configuracoes do DevTools para melhor reinicializacao
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Definindo profile como DEV
spring.profiles.active=dev

#Configuracao JWT
jwt.secret=${JWT_SECRET_BASE64}
jwt.expiration-ms=36000000
security.cors.allowed-origins=http://localhost:3000,http://localhost:8080