spring.application.name=api
server.port=8080

# Configura\u00E7\u00F5es do DevTools para melhor reinicializa\u00E7\u00E3o
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Definindo profile como DEV
spring.profiles.active=dev