#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/devdb
spring.datasource.username=${DB_LOCAL_USER}
spring.datasource.password=${DB_LOCAL_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT
jwt.secret=${JWT_SECRET_BASE64}

#Bootstrap Admin
security.bootstrap-admin.enabled=true
security.bootstrap-admin.nome=${BOOTSTRAP_ADMIN_NOME:Admin Bootstrap}
security.bootstrap-admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
security.bootstrap-admin.senha=${BOOTSTRAP_ADMIN_SENHA:}
security.bootstrap-admin.telefone=${BOOTSTRAP_ADMIN_TELEFONE:}
