# Spring config imports
spring.config.import=optional:file:../.env[.properties]

spring.application.name=api
server.port=8080

# Configuracoes do DevTools para melhor reinicializacao
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Definindo profile como DEV
spring.profiles.active=dev

#Configuracao JWT
jwt.secret=${JWT_SECRET_BASE64}
jwt.expiration-ms=36000000
security.cors.allowed-origins=http://localhost:3000,http://localhost:8080

#Log Pattern
logging.pattern.level=%5p [corr:%X{correlationId}]

# Garante que o Spring reconheca os cabecalhos do Nginx e monte os redirecionamentos de forma correta
server.forward-headers-strategy=framework