spring.datasource.url=jdbc:postgresql://localhost:5433/devdb
spring.datasource.username=${DB_LOCAL_USER}
spring.datasource.password=${DB_LOCAL_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true